# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_auto_20160921_0028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
