# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_auto_20160930_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='file',
            field=models.ImageField(default='/grumblr/images/profile.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
