# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-02 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0012_auto_20161002_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile-pic'),
        ),
    ]
