# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0013_auto_20161002_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='_userprofile_following_+', to='grumblr.UserProfile'),
        ),
    ]
