# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0014_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_confirmed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
