# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0017_auto_20161013_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2016, 10, 13, 22, 8, 58, 20821, tzinfo=utc)),
        ),
    ]
